services:
  nekolu:
    build: .
    container_name: nekolu
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_USER_ID: ${TELEGRAM_USER_ID}
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - tdlib-data:/app/tdlib
    restart: unless-stopped

volumes:
  tdlib-data:
    driver: local
